# db server group_vars
---

postgresql_max_wal_senders: 10
postgresql_wal_level: 'hot_standby' 
postgresql_hot_standby: on 
postgresql_archive_mode: on
postgresql_archive_command: '/bin/true'
postgresql_wal_keep_segments: 5000
postgresql_shared_preload_libraries: 'repmgr_funcs'
postgresql_listen_addresses: *